# Generated by Django 4.2.6 on 2023-11-13 14:01

import characters.validators.file_type
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='anime/banners/', validators=[characters.validators.file_type.FileExtensionValidator(('png', 'jpg', 'jpeg'))])),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='users/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='heroes/images/', validators=[characters.validators.file_type.FileExtensionValidator(('png',))])),
                ('top', models.CharField(max_length=4)),
                ('top_color', models.CharField(max_length=7)),
                ('bottom', models.CharField(max_length=4)),
                ('bottom_color', models.CharField(max_length=7)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.animemodel')),
                ('liked_by_users', models.ManyToManyField(related_name='liked_heroes', to='characters.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='animemodel',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_anime', to='characters.usermodel'),
        ),
    ]
